TISSUES = ['Adipose_Subcutaneous', 'Adipose_Visceral_Omentum', 'Adrenal_Gland', 'Artery_Aorta', 'Artery_Coronary',
           'Artery_Tibial', 'Brain_Amygdala', 'Brain_Anterior_cingulate', 'Brain_Caudate', 'Brain_Cerebellar',
           'Brain_Cerebellum', 'Brain_Cortex', 'Brain_Frontal_Cortex', 'Brain_Hippocampus', 'Brain_Hypothalamus',
           'Brain_Nucleus', 'Brain_Putamen', 'Brain_Spinal_cord', 'Brain_Substantia_nigra', 'Breast_Mammary_Tissue',
           'Cells_Cultured', 'Cells_EBV', 'Colon_Sigmoid', 'Colon_Transverse', 'Esophagus_Gastro', 'Esophagus_Mucosa',
           'Esophagus_Muscularis', 'Heart_Atrial', 'Heart_L_Vent', 'Kidney_Cortex', 'Liver', 'Lung', 'Minor_Salivary',
           'Muscle_Skeletal', 'Nerve_Tibial', 'Ovary', 'Pancreas', 'Pituitary', 'Prostate', 'Skin_Not_Sun_Epsd',
           'Skin_Sun_Epsd', 'Small_Intestine', 'Spleen', 'Stomach', 'Testis', 'Thyroid', 'Uterus', 'Vagina',
           'Whole_Blood']

FILES = {'Adipose_Subcutaneous': 'data/Adipose_Subcutaneous.v8.normalized_expression.bed',
         'Adipose_Visceral_Omentum': 'data/Adipose_Visceral_Omentum.v8.normalized_expression.bed',
         'Adrenal_Gland': 'data/Adrenal_Gland.v8.normalized_expression.bed',
         'Artery_Aorta': 'data/Artery_Aorta.v8.normalized_expression.bed',
         'Artery_Coronary': 'data/Artery_Coronary.v8.normalized_expression.bed',
         'Artery_Tibial': 'data/Artery_Tibial.v8.normalized_expression.bed',
         'Brain_Amygdala': 'data/Brain_Amygdala.v8.normalized_expression.bed',
         'Brain_Anterior_cingulate': 'data/Brain_Anterior_cingulate_cortex_BA24.v8.normalized_expression.bed',
         'Brain_Caudate': 'data/Brain_Caudate_basal_ganglia.v8.normalized_expression.bed',
         'Brain_Cerebellar': 'data/Brain_Cerebellar_Hemisphere.v8.normalized_expression.bed',
         'Brain_Cerebellum': 'data/Brain_Cerebellum.v8.normalized_expression.bed',
         'Brain_Cortex': 'data/Brain_Cortex.v8.normalized_expression.bed',
         'Brain_Frontal_Cortex': 'data/Brain_Frontal_Cortex_BA9.v8.normalized_expression.bed',
         'Brain_Hippocampus': 'data/Brain_Hippocampus.v8.normalized_expression.bed',
         'Brain_Hypothalamus': 'data/Brain_Hypothalamus.v8.normalized_expression.bed',
         'Brain_Nucleus': 'data/Brain_Nucleus_accumbens_basal_ganglia.v8.normalized_expression.bed',
         'Brain_Putamen': 'data/Brain_Putamen_basal_ganglia.v8.normalized_expression.bed',
         'Brain_Spinal_cord': 'data/Brain_Spinal_cord_cervical_c-1.v8.normalized_expression.bed',
         'Brain_Substantia_nigra': 'data/Brain_Substantia_nigra.v8.normalized_expression.bed',
         'Breast_Mammary_Tissue': 'data/Breast_Mammary_Tissue.v8.normalized_expression.bed',
         'Cells_Cultured': 'data/Cells_Cultured_fibroblasts.v8.normalized_expression.bed',
         'Cells_EBV': 'data/Cells_EBV-transformed_lymphocytes.v8.normalized_expression.bed',
         'Colon_Sigmoid': 'data/Colon_Sigmoid.v8.normalized_expression.bed',
         'Colon_Transverse': 'data/Colon_Transverse.v8.normalized_expression.bed',
         'Esophagus_Gastro': 'data/Esophagus_Gastroesophageal_Junction.v8.normalized_expression.bed',
         'Esophagus_Mucosa': 'data/Esophagus_Mucosa.v8.normalized_expression.bed',
         'Esophagus_Muscularis': 'data/Esophagus_Muscularis.v8.normalized_expression.bed',
         'Heart_Atrial': 'data/Heart_Atrial_Appendage.v8.normalized_expression.bed',
         'Heart_L_Vent': 'data/Heart_Left_Ventricle.v8.normalized_expression.bed',
         'Kidney_Cortex': 'data/Kidney_Cortex.v8.normalized_expression.bed',
         'Liver': 'data/Liver.v8.normalized_expression.bed',
         'Lung': 'data/Lung.v8.normalized_expression.bed',
         'Minor_Salivary': 'data/Minor_Salivary_Gland.v8.normalized_expression.bed',
         'Muscle_Skeletal': 'data/Muscle_Skeletal.v8.normalized_expression.bed',
         'Nerve_Tibial': 'data/Nerve_Tibial.v8.normalized_expression.bed',
         'Ovary': 'data/Ovary.v8.normalized_expression.bed',
         'Pancreas': 'data/Pancreas.v8.normalized_expression.bed',
         'Pituitary': 'data/Pituitary.v8.normalized_expression.bed',
         'Prostate': 'data/Prostate.v8.normalized_expression.bed',
         'Skin_Not_Sun_Epsd': 'data/Skin_Not_Sun_Exposed_Suprapubic.v8.normalized_expression.bed',
         'Skin_Sun_Epsd': 'data/Skin_Sun_Exposed_Lower_leg.v8.normalized_expression.bed',
         'Small_Intestine': 'data/Small_Intestine_Terminal_Ileum.v8.normalized_expression.bed',
         'Spleen': 'data/Spleen.v8.normalized_expression.bed',
         'Stomach': 'data/Stomach.v8.normalized_expression.bed',
         'Testis': 'data/Testis.v8.normalized_expression.bed',
         'Thyroid': 'data/Thyroid.v8.normalized_expression.bed',
         'Uterus': 'data/Uterus.v8.normalized_expression.bed',
         'Vagina': 'data/Vagina.v8.normalized_expression.bed',
         'Whole_Blood': 'data/Whole_Blood.v8.normalized_expression.bed'}
